# -*- coding: utf-8 -*-
"""
backend/app/services/analytics/models.py

Pydantic data models for Analytics Service — Stage 5.

Defines schemas for:
- OverviewAnalytics: Cohort-level KPI summary
- ChannelAnalytics: Per-channel engagement and conversion performance
- AttributionChannel: Channel credit and attributed revenue breakdown
- AttributionAnalytics: Single-model attribution results
- AttributionComparison: Multi-model attribution comparison table
- JourneyPattern: Channel path sequence analysis and conversion rates
"""

from typing import Optional
from pydantic import BaseModel, Field


class OverviewAnalytics(BaseModel):
    """High-level marketing and journey performance metrics across all customers."""
    customers: int = Field(..., description="Total unique customers in the platform")
    events: int = Field(..., description="Total interaction events recorded")
    sessions: int = Field(..., description="Total computed customer sessions")
    conversions: int = Field(..., description="Total number of converting customers")
    conversion_rate: float = Field(..., description="Fraction of customers who converted (conversions / customers)")
    total_revenue: float = Field(..., description="Total monetary revenue generated from conversions")
    average_order_value: float = Field(..., description="Average revenue per conversion (total_revenue / conversions)")
    average_journey_duration_minutes: float = Field(..., description="Average journey duration across customers")
    average_touchpoints: float = Field(..., description="Average marketing touchpoint count per customer")
    unique_channels: int = Field(..., description="Count of distinct marketing channels observed")


class ChannelAnalytics(BaseModel):
    """Performance metrics for an individual marketing channel."""
    channel: str = Field(..., description="Marketing channel name")
    customers: int = Field(..., description="Unique customers who engaged with this channel")
    events: int = Field(..., description="Total events logged under this channel")
    sessions: int = Field(..., description="Total sessions where this channel was touched")
    conversions: int = Field(..., description="Count of converting customers who engaged with this channel")
    conversion_rate: float = Field(..., description="Channel conversion rate (conversions / customers)")
    revenue: float = Field(..., description="Total conversion revenue from customers touching this channel")
    average_revenue: float = Field(..., description="Average revenue per converting customer (revenue / conversions)")


class AttributionChannel(BaseModel):
    """Credit and monetary revenue attributed to a single channel."""
    channel: str = Field(..., description="Marketing channel name")
    credit: float = Field(..., description="Attribution share/weight (sums to 1.0 across channels)")
    attributed_revenue: float = Field(..., description="Monetary conversion revenue allocated to this channel")


class AttributionAnalytics(BaseModel):
    """Aggregated attribution results for a specific attribution model."""
    model: str = Field(..., description="Attribution model name (e.g. 'linear', 'markov')")
    total_revenue: float = Field(..., description="Total conversion revenue attributed")
    channels: list[AttributionChannel] = Field(default_factory=list, description="Per-channel attribution allocations")


class AttributionComparison(BaseModel):
    """Multi-model attribution results for side-by-side comparative analysis."""
    models: dict[str, list[AttributionChannel]] = Field(
        ...,
        description="Map of model name to list of AttributionChannel objects",
    )
    total_revenue: Optional[float] = Field(None, description="Total conversion revenue across the evaluated cohort")


class JourneyPattern(BaseModel):
    """Aggregated performance metrics for a specific sequential channel path."""
    path: list[str] = Field(..., description="Ordered sequence of marketing channels (order preserved)")
    customers: int = Field(..., description="Number of customers who followed this exact path")
    conversions: int = Field(..., description="Number of conversions that occurred along this path")
    conversion_rate: float = Field(..., description="Path conversion rate (conversions / customers)")
    revenue: float = Field(..., description="Total conversion revenue generated by this path")
    average_journey_duration_minutes: float = Field(..., description="Average duration of journeys with this path")
    average_touchpoints: float = Field(..., description="Average touchpoint count along this path")
